### ISSUE TITLE
multiple scanner 

### ISSUE THREAD

**Issue by mai-alhashmi** [Eng-Mohamed-Elsayed/Month-Day#3]
in method get name month and method get day

**Comment by Eng-Mohamed-Elsayed** [comment]
can send code method 
more details 😁

**Comment by mai-alhashmi** [comment]
` public static String getNameMonth() {
        Scanner scanner = new Scanner(System.in);`

**Comment by Mohammad-Nabelsi-IT** [comment]
`public static String getNameDay() {
        Scanner scanner = new Scanner(System.in);`

**Comment by Mohammad-Nabelsi-IT** [comment]
FIX Problem pull request

**Comment by Eng-Mohamed-Elsayed** [comment]
@Mohammad-Nabelsi-IT thanks for solving the problem it works now 🌹

**Comment by Eng-Mohamed-Elsayed** [comment]
@Mohammad-Nabelsi-IT thanks for solving the problem it works now 🌹
